spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource			#datasource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/accountBook?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1472580369
   # password: tsyjzqcD10

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl	#开启显示sql语句

